NETWORK_PARAMS={"poolers":[
                           {"name":"spCostsRegion", 
                            "type":"py.SPRegion",
                            "learningMode":True,
                            "anomalyMode":True,
                            "params": { 'columnCount': 2048,
                                        'globalInhibition': 1,
                                        'inputWidth': 3200,
                                        'maxBoost': 5.0,
                                        'numActiveColumnsPerInhArea': 61,
                                        'potentialPct': 0.8,
                                        'potentialRadius': 16,
                                        #'stimulusThreshold': 5,
                                        'seed': 1956,
                                        'spVerbosity': 0,
                                        'spatialImp': 'cpp',
                                        'synPermActiveInc': 0.05,
                                        'synPermConnected': 0.1,
                                        'synPermInactiveDec': 0.0121}
                            },
                           {
                            "name":"tpCostsRegion",
                            "type":"py.TPRegion",
                            "topDownMode":True,
                            "inferenceMode":True,
                            "learningMode":True,
                            "anomalyMode":True,
                            "params": { 'activationThreshold': 12,
                                        'cellsPerColumn': 1,
                                        'columnCount': 2048,
                                        'globalDecay': 0.0,
                                        'initialPerm': 0.21,
                                        'inputWidth': 2048,
                                        'maxAge': 0,
                                        'permanenceDec': 0.1,
                                        'permanenceInc': 0.1,
                                        'seed': 1960,
                                        'temporalImp': 'cpp',
                                        'verbosity': 0, 
                                        'outputType' : 'activeState' }
                            },
                           {"name":"spPPGSRegion", 
                            "type":"py.SPRegion",
                            "learningMode":True,
                            "anomalyMode":True,
                            "params": { 'columnCount': 2048,
                                        'globalInhibition': 1,
                                        'inputWidth': 2800,
                                        'maxBoost': 5.0,
                                        'numActiveColumnsPerInhArea': 61,
                                        'potentialPct': 0.8,
                                        'potentialRadius': 16,
                                        #'stimulusThreshold': 5,
                                        'seed': 1956,
                                        'spVerbosity': 0,
                                        'spatialImp': 'cpp',
                                        'synPermActiveInc': 0.05,
                                        'synPermConnected': 0.1,
                                        'synPermInactiveDec': 0.0121}
                            },
                           {
                            "name":"tpPPGSRegion",
                            "type":"py.TPRegion",
                            "topDownMode":True,
                            "inferenceMode":True,
                            "learningMode":True,
                            "anomalyMode":True,
                            "params": { 'activationThreshold': 12,
                                        'cellsPerColumn': 1,
                                        'columnCount': 2048,
                                        'globalDecay': 0.0,
                                        'initialPerm': 0.21,
                                        'inputWidth': 2048,
                                        'maxAge': 0,
                                        'permanenceDec': 0.1,
                                        'permanenceInc': 0.1,
                                        'seed': 1960,
                                        'temporalImp': 'cpp',
                                        'verbosity': 0, 
                                        'outputType' : 'activeState' }
                            },
                           {"name":"spReefersRegion", 
                            "type":"py.SPRegion",
                            "learningMode":True,
                            "anomalyMode":True,
                            "params": { 'columnCount': 2048,
                                        'globalInhibition': 1,
                                        'inputWidth': 2400,
                                        'maxBoost': 5.0,
                                        'numActiveColumnsPerInhArea': 61,
                                        'potentialPct': 0.8,
                                        'potentialRadius': 16,
                                        #'stimulusThreshold': 5,
                                        'seed': 1956,
                                        'spVerbosity': 0,
                                        'spatialImp': 'cpp',
                                        'synPermActiveInc': 0.05,
                                        'synPermConnected': 0.1,
                                        'synPermInactiveDec': 0.0121}
                            },
                           {
                            "name":"tpReefersRegion",
                            "type":"py.TPRegion",
                            "topDownMode":True,
                            "inferenceMode":True,
                            "learningMode":True,
                            "anomalyMode":True,
                            "params": { 'activationThreshold': 12,
                                        'cellsPerColumn': 1,
                                        'columnCount': 2048,
                                        'globalDecay': 0.0,
                                        'initialPerm': 0.21,
                                        'inputWidth': 2048,
                                        'maxAge': 0,
                                        'permanenceDec': 0.1,
                                        'permanenceInc': 0.1,
                                        'seed': 1960,
                                        'temporalImp': 'cpp',
                                        'verbosity': 0, 
                                        'outputType' : 'activeState' }
                            },
                           {"name":"spTopRegion", 
                            "type":"py.SPRegion",
                            "learningMode":True,
                            "anomalyMode":True,
                            "params": { 'columnCount': 2048,
                                        'globalInhibition': 1,
                                         'inputWidth': 6144,
                                         'maxBoost': 5,
                                         'numActiveColumnsPerInhArea': 42,
                                         'potentialPct': 0.9,
                                         'potentialRadius': 32,
                                         'globalInhibition': 1,
                                         'seed': 1926,
                                         'spVerbosity': 0,
                                         'spatialImp': 'cpp',
                                         'synPermActiveInc': 0.05,
                                         'synPermConnected': 0.1,
                                         'synPermInactiveDec': 0.0125}
                            },
                           {
                            "name":"tpTopRegion",
                            "type":"py.TPRegion",
                            "topDownMode":True,
                            "inferenceMode":True,
                            "learningMode":True,
                            "anomalyMode":True,
                            "params": { 'cellsPerColumn': 1,
                                 'columnCount': 2048,
                                 'globalDecay': 0.0,
                                 'initialPerm': 0.21,
                                 'inputWidth': 2048,
                                 #'maxAge': 0,
                                 #'maxSegmentsPerCell': 128,
                                 #'maxSynapsesPerSegment': 32,
                                 #'minThreshold': 10,
                                 #'pamLength': 1,
                                 'newSynapseCount': 20,
                                 'permanenceDec': 0.1,
                                 'permanenceInc': 0.1,
                                 'seed': 1932,
                                 'temporalImp': 'cpp',
                                 'verbosity': 0, }
                            },
                           ],
                "sensors":[        
                           {"name":"Costs",
                            "params":{ 'verbosity': 0 },
                            "type":"py.RecordSensor",
                           "encodings":{ 'GALLONS':       { 'name': 'GALLONS',    'fieldname': 'FMDL_TR_TRACTOR_GALLONS', 'resolution': 2.0, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'TRACTOR_COST':  { 'name': 'TRACTOR_COST', 'fieldname': 'FMDL_SC_TR_TRACTOR_COST', 'resolution': 5.0, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'FUEL_RATE':  { 'name': 'FUEL_RATE', 'fieldname': 'FMDL_RD_FUEL_RATE', 'resolution': 0.001, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'PROD_CODE':     { 'name': 'PROD_CODE',  'fieldname': 'FMDL_NR2_SUB_PROD_CODE', 'n': 400, 'w': 21, 'forced': 'True', 'type': 'SDRCategoryEncoder' }, 
                                        'SC_CODE':       { 'name': 'SC_CODE',  'fieldname': 'FMDL_SETTLEMENT_SC_CODE', 'n': 400, 'w': 21, 'forced': 'True', 'type': 'SDRCategoryEncoder' }, 
                                        'SC_DISCOUNT':   { 'name': 'SC_DISCOUNT', 'fieldname': 'FMDL_RD_SC_SELECT_DISCOUNT', 'resolution': 0.01, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'TRAN_FEE':        { 'name': 'TRAN_FEE', 'fieldname': 'FMDL_RD_SC_TRANSACTION_FEE', 'resolution': 0.01, 'type': 'RandomDistributedScalarEncoder' }, 
                                        # 'UNIT_NUM':        { 'name': 'UNIT_NUM', 'fieldname': 'FMDL_DT_UNIT_NUMBER', 'resolution': 1, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'COMDATA_FEES':  { 'name': 'COMDATA_FEES', 'fieldname': 'FMDL_COMDATA_FEES', 'resolution': 0.01, 'type': 'RandomDistributedScalarEncoder' }},
                                        "source":"./Swift3.csv"
                            },
                           {"name":"PPGS",
                            "params":{ 'verbosity': 0 },
                             "type":"py.RecordSensor",
                           "encodings":{ 'TRACTOR_PPG':   { 'name': 'TRACTOR_PPG', 'fieldname': 'FMDL_SC_TR_TRACTOR_PPG', 'resolution': 0.001, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'TRAN_PPG':        { 'name': 'TRAN_PPG', 'fieldname': 'FMDL_CP_DIESEL_TRAN_PPG', 'resolution': 0.001, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'PPG_NR2':    { 'name': 'PPG_NR2', 'fieldname': 'FMDL_RETAIL_PPG_NR2', 'resolution': 0.01, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'PLUS_PPG':      { 'name': 'PLUS_PPG',  'fieldname': 'FMDL_COST_PLUS_NR2_PPG', 'resolution': 0.001, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'RACK_PPG':      { 'name': 'RACK_PPG',  'fieldname': 'FMDL_CP_NR2_RACK_PPG', 'resolution': 0.001, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'LUST_PPG':      { 'name': 'LUST_PPG',  'fieldname': 'FMDL_CP_DIESEL_LUST_PPG', 'resolution': 0.001, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'TAX_PPG':      { 'name': 'TAX_PPG',  'fieldname': 'FMDL_CP_DIESEL_ST_TAX_PPG', 'resolution': 0.001, 'type': 'RandomDistributedScalarEncoder' }}, 
                            "source":"./Swift3.csv"
                            },
                            {"name":"Reefers",
                            "params":{ 'verbosity': 0 },
                             "type":"py.RecordSensor",
                             "encodings":{ 'ST_TAX_PPG':      { 'name': 'ST_TAX_PPG',  'fieldname': 'FMDL_CP_REEFER_ST_TAX_PPG', 'resolution': 0.001, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'MISC_PPG':      { 'name': 'MISC_PPG',  'fieldname': 'FMDL_CP_REEFER_MISC_PPG', 'resolution': 0.001, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'TRAN_PPG':      { 'name': 'TRAN_PPG',  'fieldname': 'FMDL_CP_REEFER_TRAN_PPG', 'resolution': 0.001, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'ST_PPG':      { 'name': 'ST_PPG',  'fieldname': 'FMDL_CP_REEFER_ST_SF_PPG', 'resolution': 0.001, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'MISC_PPG':      { 'name': 'MISC_PPG',  'fieldname': 'FMDL_CP_REEFER_MISC_PPG', 'resolution': 0.001, 'type': 'RandomDistributedScalarEncoder' }, 
                                        'REEFER_LUST_PPG': { 'name': 'REEFER_LUST_PPG', 'fieldname': 'FMDL_CP_REEFER_LUST_PPG', 'resolution': 0.001, 'type': 'RandomDistributedScalarEncoder' }},
                            "source":"./Swift3.csv" 
                             },
                           ],
                "links":[
                         #SP to tp Top
                         {"source":"spTopRegion",
                          "destination":"tpTopRegion",
                          "type":"UniformLink",
                          "params":""
                          },  
                         
                         #Sensors to SPs                      
                         {"source":"Costs",
                          "destination":"spCostsRegion",
                          "type":"UniformLink",
                          "params":""
                          },
                         {"source":"PPGS",
                          "destination":"spPPGSRegion",
                          "type":"UniformLink",
                          "params":""
                          },
                         {"source":"Reefers",
                          "destination":"spReefersRegion",
                          "type":"UniformLink",
                          "params":""
                          },
                         #Sps to TPs lower regions
                          {"source":"spPPGSRegion",
                          "destination":"tpPPGSRegion",
                          "type":"UniformLink",
                          "params":""
                          },
                          {"source":"spReefersRegion",
                          "destination":"tpReefersRegion",
                          "type":"UniformLink",
                          "params":""
                          },
                          {"source":"spCostsRegion",
                          "destination":"tpCostsRegion",
                          "type":"UniformLink",
                          "params":""
                          },
                         #Lower TPs to upper SPs
                         {"source":"tpCostsRegion",
                          "destination":"spTopRegion",
                          "type":"UniformLink",
                          "params":""
                          },
                         {"source":"tpPPGSRegion",
                          "destination":"spTopRegion",
                          "type":"UniformLink",
                          "params":""
                          },
                         {"source":"tpReefersRegion",
                          "destination":"spTopRegion",
                          "type":"UniformLink",
                          "params":""
                          },
                         ]
                }